import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"
startup_mode = "Windowed"
#startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"

[window.dimensions]
columns = 140
lines = 40

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 17
